SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE User;

ALTER TABLE User ADD COLUMN contactNo VARCHAR(15) UNIQUE NOT NULL ;

ALTER TABLE Person DROP COLUMN contactNo,ADD COLUMN userId INT NOT NULL REFERENCES User(userId);

ALTER TABLE Doctor DROP COLUMN contactNo,ADD COLUMN userId INT NOT NULL REFERENCES User(userId);

ALTER TABLE Hospital DROP COLUMN hospitalAdminContactNo,ADD COLUMN userId INT NOT NULL REFERENCES User(userId);

DROP TABLE DoctorDiseaseMap;

SET FOREIGN_KEY_CHECKS = 1;
